### PR TITLE
Feature/aphrodite

### PR DESCRIPTION
**Pull request by koz**

### CODE REVIEW

**Comment by firstdoit** [comment]
Hmm why delete `package.json`? It has tests configured.

**Comment by koz** [comment]
@amoreira said it wasn't going to be used anymore.

**Comment by firstdoit** [comment]
Until we have a way to test render source code in the platform, we must test offline.

**Comment by koz** [comment]
@firstdoit reverted.

**Comment by firstdoit** [comment]
LGTM!

**Pull request merged**
